name: CI
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ESLint
      run: npm i && npm run lint
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit test
      run: npm i jest && npm run test
